cyverse-de/data-info

src/data_info/services/sharing.clj

At least some genome browsers do funny stuff with spaces, so it's better to have this be a totally bona-fide URL with escaping and such. I'm doing the split-then-rejoin thing because we don't want to encode slashes, though.

CORE-6067: url-encode path parts in anon-files URLs sent to the UI

---

src/data_info/services/uuids.clj

This caused a regression error at (at least): https://shimerdas.iplantcollaborative.org:8443/job/DE_QA-3/237/robot/report/log.html#s1-s4-s44-t25-k9
I didn't check if there were other places in the regression this affected, but I did check that all places that use `path-for-uuid` should be throwing an error when the UUID they're calling it for doesn't exist.

Throw appropriate ERR_DOES_NOT_EXIST when data-info.services.uuids/path-for-uuid is used

---

src/data_info/routes/navigation.clj
src/data_info/routes/schemas/navigation.clj
src/data_info/services/root.clj

This PR adds a new `GET /navigation/base-paths` endpoint that returns the absolute paths of the user's home directory, trash, and the base trash path:
```json
{
"user_home_path": "string",
"user_trash_path": "string",
"base_trash_path": "string"
}
```
This information was previously generated by terrain's `bootstrap` endpoint, but terrain will now defer to this endpoint for this info.
Also updated `GET /navigation/root` to include a `base-paths` field, which includes this info as well. This will help the UI retrieve this info later if the `bootstrap` endpoint could not initially retrieve it at user login.

CORE-7813 Add GET /navigation/base-paths

---

project.clj
src/data_info/clients/metadata.clj
src/data_info/routes/avus.clj
src/data_info/routes/data.clj
src/data_info/routes/middleware.clj
src/data_info/services/metadata.clj
src/data_info/util/config.clj

Updates for the new protocol version of `metadata-client` added by cyverse-de/metadata-client#1.
Includes a new `data-info.clients.metadata` to facade calls to `metadata-client`.

CORE-8487 Update to new protocol version of metadata-client

---

src/data_info/util/irods.clj

Prevents potential `JargonException` "Unknown iRODS exception code recieved:-510024" in `stat-gatherer` and `metadata` save endpoints (and others?).

CORE-8949 Prevent potential "Too many open files" error.

---

data-info.properties.tmpl
src/data_info/routes.clj
src/data_info/routes/path_lists.clj
src/data_info/routes/schemas/path_lists.clj
src/data_info/services/filetypes.clj
src/data_info/services/path_lists.clj
src/data_info/util/config.clj
src/data_info/util/paths.clj
src/data_info/util/validators.clj
test/data_info/services/path_lists_tests.clj

This PR adds the `POST /path-list-creator` endpoint, which will generate an HT Path List file for all paths under the given set of folder paths, saving the results to the given destination file.
The paths for folders given in the request will not be included in the results, but if any file paths are included in the request, those paths will also be processed according to the other given parameters:
* `recursive`: When set to true, then paths under all subfolders will also be processed recursively.
* `folders-only`: When set to true, then only paths for folders will be included in the results, otherwise only file paths will be included.
* `name-pattern`: Specifying a regex pattern will filter the results to include only file/folder names that match this pattern.
* `info-type`: Specifying …

CORE-8945 Add `POST /path-list-creator`

---

src/data_info/routes.clj
src/data_info/routes/schemas/users.clj
src/data_info/routes/users.clj
src/data_info/services/users.clj

This should be relatively straightforward to review. We need this because the search service needs to add a clause limiting the search to data the user can actually see. So, given a user, it needs a way to find the user's full qualified name a la `mian#iplant` and the qualified names of all the groups the user is part of, which can then be passed to the clause it adds to do that filtering.
I may or may not update terrain's existing search stuff to use this endpoint as well; it needs migration out of terrain for now, but the code that needs this won't be in terrain at all after the search refactor, so it might not be worth the bother.

CORE-6259, CORE-7930: Add a user groups endpoint to data-info for use by the search services

---

data-info.properties.tmpl
project.clj
src/data_info/routes/schemas/common.clj
src/data_info/services/path_lists.clj
src/data_info/util/config.clj

This PR will add Multi-Input Path List identifier config settings and cleanup existing HT Path List config settings.
cyverse-de/heuristomancer#4 should be merged first.

CORE-9063 Add Multi-Input Path List identifier config settings.

---

src/data_info/routes/schemas/path_lists.clj
src/data_info/services/path_lists.clj

This PR will add Multi-Input Path List support, and a new `path-list-info-type` query parameter, to the `path-list-creator` endpoint.

CORE-9064 Add Multi-Input Path List support to `path-list-creator` endpoint.

---

src/data_info/routes/schemas/tickets.clj
src/data_info/routes/tickets.clj
src/data_info/services/tickets.clj

Submitting jobs to OSG requires the ability to generate read tickets for input files, and we don't want to prevent users from using input files for which they only have `read` permissions. The chosen solution, for the time being, is to allow these tickets to be generated only for the purpose of a job. We're using a query parameter to indicate that the ticket is being generated for a job, and the `apps` service will be modified to send the query parameter. Externally facing endpoints should not be modified to expose this parameter for the sake of security.

Allow tickets to be generated for paths with read permissions.

---

project.clj
src/data_info/routes/navigation.clj
src/data_info/routes/schemas/navigation.clj

This PR will replace the `data-info.routes.schemas.navigation/UserBasePaths` schema with the schema added by cyverse-de/common-swagger-api#30.

CORE-11 Migrate /navigation/base-paths schemas

---

project.clj
src/data_info/routes/schemas/tickets.clj
src/data_info/routes/tickets.clj

This PR will replace the ticket endpoint schemas and docs in `data-info.routes.schemas.tickets` and `data-info.routes.tickets` with those imported in cyverse-de/common-swagger-api#49.

CORE-9 Migrate ticket endpoint schemas and docs.

---

src/data_info/clients/async_tasks.clj
src/data_info/routes/schemas/trash.clj
src/data_info/services/rename.clj
src/data_info/services/trash.clj

Things included here:
* delete, restore, and delete-trash async
* number-of-path validators removed
* removing some extra, unneeded validators
* code reorganization/utility function stuff

Async delete and restore (CORE-558 part 2)

---

src/data_info/routes/schemas/stats.clj
src/data_info/services/stat.clj

The purpose of this change is to speed up the permanent ID request endpoint in terrain. Terrain is currently performing a separate API call to get the path information for each permanent ID request, which can be sluggish when the data store is under a heavy load. As far as I can tell, the only reason that separate API calls are being made is because there's a chance that the paths related to some permanent ID requests either no longer exist or aren't accessible to the administrator doing the listing. Making separate API calls, allows terrain to effectively ignore errors for missing or inaccessible files. Allowing all of these requests to be combined into a single API call will speed things up dramatically.
The changes to the endpoint are as follows:
* Two new query parameters have been …

CORE-1094: allow the path-info endpoint to optionally ignore missing or inaccessible paths or IDs

---

src/data_info/clients/async_tasks.clj
src/data_info/clients/notifications.clj
src/data_info/services/rename.clj
src/data_info/services/trash.clj
src/data_info/util/config.clj

Sends notifications at the end of moves, renames, move to trash, restore from trash, and emptying trash.

Add notifications for async task completions

---

project.clj
src/data_info/services/entry.clj
src/data_info/util/irods.clj

Pretty straightforward, I think. As you might expect, depends a decent bit on https://github.com/cyverse-de/clj-irods/pull/1, which depends on https://github.com/cyverse-de/clj-jargon/pull/10 and https://github.com/cyverse-de/clj-icat-direct/pull/7
But, this improves performance a pretty significant amount, especially for smaller folders, given that it means listings don't need to set up an irods connection at all. Should be some benefits for file viewing too.

Improve listing performance using clj-irods

---

project.clj
src/data_info/services/uuids.clj

Uses the conjunction of https://github.com/cyverse-de/clj-irods/pull/2 https://github.com/cyverse-de/clj-icat-direct/pull/8 and https://github.com/cyverse-de/clj-jargon/pull/11 to dramatically speed up the "uuid for path" endpoint, which is used by... a lot, because right now anything in data-info that takes only UUIDs where terrain takes a path, terrain has to get the UUID from this endpoint first.
In my testing, this takes the response time from sometimes as long as a second, down to what seems to usually be 70-80ms.

Speed up do-simple-uuid-for-path with clj-irods

---

src/data_info/routes/data.clj
src/data_info/services/write.clj

Right now, could still use some improvement, but it does:
a.) Reduce to one clj-jargon connection by way of me figuring out how multipart stuff works better than I did a few years ago when I wrote this code
b.) change validations to use clj-irods
c.) instrument with opentelemetry
More to come, possibly.

Optimize save/overwrite endpoints with clj-irods and some other tweaks

---

project.clj
src/data_info/services/root.clj

Uses the changes in cyverse-de/clj-irods#5 to ensure that when `make-root` needs to create a path or set ownership on it (the trash path, incidentally), it invalidates cached results for the path afterwards so they're re-fetched.

Fix roots endpoint: invalidate cached values in make-root when changes are made

---

src/data_info/services/entry.clj

This indicates the presence of a readme by returning a filename, or absence by returning false.
Pretty straightforward, really. We ensure that the listing itself has come back already, because then if the readme files being checked appear within the page, it doesn't need to hit IRODS or the ICAT to confirm they exist.

CORE-1178: Add a readme flag to listings

---

project.clj
src/data_info/services/write.clj
src/data_info/util/config.clj

Seeking input on this. In my rudimentary testing, this adds about 250ms to the endpoint response time due to the call to `add-metadata`. Actually detecting the info-type, from the upload's `InputStream`, is done in a future and so doesn't add to the time meaningfully. The `decorate-stat` still takes about 350ms, plus ~80ms that is moved from the decorate-stat to the new code (the code that fetches existing info-types). The post-upload code (the stat/decorate-stat/this) could probably be faster for read-only operations by using clj-irods (now that invalidation is a thing), but this 250ms or so would be unchanged. Basically, I'm wondering if it seems worth splitting this into an async task. The file upload itself overshadows this significantly, and will more the larger the file.

Set info-type on upload

---

project.clj
src/data_info/core.clj
src/data_info/services/directory.clj
src/data_info/services/home.clj
src/data_info/services/metadata.clj
src/data_info/services/path_lists.clj
src/data_info/services/stat.clj
src/data_info/services/stat/common.clj
src/data_info/services/stat/jargon.clj
src/data_info/services/write.clj

While I was modifying the stat-gatherer endpoint, I also made the following changes.
- Updated some dependencies.
- Removed the code to set up the nrepl port, which wasn't being used.
- Migrated the `/navigation/path/:zone/:path` endpoint over to clj-irods.
- Migrated the `/navigation/home` endpoint over to clj-irods.
- Moved the old stat formatting code that uses `clj-jargon` over to a new namespace: `data-info.services.stat.jargon`.
- Moved functions shared by both stat formatting namespaces to another new namespace: `data-info.services.stat.common`.

CORE-1249: use clj-irods to obtain information for the stat-gatherer endpoint.

---

.gitignore
project.clj

This change is just my usual method for making it easier for me to test code changes with CIDER. I don't think I'm going to modify `data-info` for this issue, but since I was experimenting with possibly updating `data-info` today, I figured I'd submit the PR to get these changes into the main repo.

CORE-1430: make it easier to test code changes in the REPL

---

src/data_info/services/sharing.clj

A little bit annoying, but this seems to work with what I've tried it with.
The main annoyance is that java.net.URLEncoder turns spaces into `+` characters. However, since it turns `+` into `%2B`, we can just do a string replace afterwards to get what we want, hacky though it feels. Other than the space-plus thing, it does what we want. Of course, we also don't want to encode the slashes, so I split on those and then re-join the path on them.
It probably won't matter either way, but I've set it up to do this after mapping the path to the appropriate webdav URL. It won't come up with anything we're running, but it could ostensibly matter if we wanted to map something with a space or other needing-url-encoding character to a different path before returning it; this way, the config file uses …

CORE-1462: url-encode paths for anonymous access

---

src/data_info/services/rename.clj
src/data_info/services/trash.clj

This should mean that if, say, someone moves an analysis from the analyses folder to their home folder, it'll only lock the actual destination, not the entire home directory.
I'm not sure if this is sufficient, so I'd love some thoughts on potential ways of breaking this (I'll be doing so too, of course).

CORE-1752 cont.: Make more precise conflict lists for moves

---

src/data_info/clients/async_tasks.clj

I wasn't sure if I should add separate functions for the task of "retry <some action> a few times and then continue if it fails", or possibly add a variant of `retry` that accepts a function to call with the exception after the retries finish (that we can pass a logging function or other no-op to if we want to continue on failure). Opinions welcome!

Add retry behavior to the status-adding in clients.async-tasks

---

src/data_info/clients/async_tasks.clj

(for the intermediate updates -- start and end statuses it'll run it in the thread pool but wait for it to return before continuing/exiting)
This is also so I can add a sleep in so it won't just spam async-tasks as fast as it can when it ends up needing to retry.
Also, hopefully this is the last PR for this for a while :sweat_smile:

Do async-tasks service updates in a thread pool to allow them to be non-blocking

---

project.clj
src/data_info/routes.clj
src/data_info/routes/groups.clj
src/data_info/services/groups.clj
src/data_info/services/users.clj
src/data_info/util/validators.clj

This depends on cyverse-de/clj-jargon#15 and once that's merged I'll update the version number here.
This adds CRUD endpoints for groups in IRODS, to be used by the indexing service that will sync Grouper groups into IRODS.

IRODS Groups API

---

project.clj
src/data_info/services/sharing.clj
src/data_info/util/paths.clj

This PR will also update calls to `clj-jargon.item-info/trash-base-dir`, which no longer requires a user param, so that items can be put into the same trash paths as used by `irm`.

CORE-1893 Update clj-jargon to v3.1.0

---

src/data_info/services/groups.clj

This doesn't do everything within CORE-2004 because it doesn't alert admins when users are missing. I'm not sure how critical that is to include.

CORE-2004: filter the list of members by existence in iRODS rather than erroring

---

project.clj

This is a minor change to switch to a new version of `org.clojure/dire`. While I was at it, I also switched to a new version of Clojure that was just released.

CORE-2006: update the `dire` dependency again

---

project.clj

This change fixes the `{:distinct nil}` error messages that we've been seeing in the data listing page.

CORE-2008: bumped the clj-irods and clj-icat-direct versions

---

src/data_info/services/groups.clj

This function takes two arguments, the connection and the user, not just the user.

Fix user-exists? arity issue

---

skaffold.yaml
src/data_info/routes/groups.clj
src/data_info/services/groups.clj

We kept getting `(not (map? nil))` errors, and I didn't have any luck telling schema to just ignore that and return an empty response instead. I ended up making up a response body and returning it instead.

Fix a schema validation error for group deletion requests.

---

project.clj

Thankfully, this only requires dependency updates.

CORE-2072: switch to a newer version of Jargon.
